import { sitePath } from '@/lib/site-path';
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Website Privacy | GWC Information Systems, LLC' };
export default function Privacy() {
return <main className="legal-page container"><a href={sitePath('/')}>Back to GWC Information Systems</a><h1>Website privacy</h1><p className="legal-date">Effective September 7, 2026</p><p>This is an informational website for GWC Information Systems, LLC. GWC does not collect personal information through this website, run analytics or advertising, or sell or share visitor information for advertising.</p><h2>Information and contact links</h2><p>This website has no inquiry form, newsletter registration, checkout, or file upload. Selecting an email or telephone link opens your email or calling application. If you contact GWC, the information you choose to provide is sent through that service to GWC.</p><h2>Hosting and external services</h2><p>This site is hosted using {process.env.GITHUB_PAGES_BUILD === '1' ? 'GitHub Pages' : 'OpenAI Sites'}. Hosting and access services may process technical information, such as IP addresses, request logs, and sign-in information, to deliver and protect the site. Their handling of information is described in <a href={process.env.GITHUB_PAGES_BUILD === '1' ? 'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement' : 'https://openai.com/policies/privacy-policy/'}>the hosting provider’s privacy policy</a>. Google Maps and LinkedIn links take you to external services with their own privacy practices.</p><h2>Cookies and tracking preferences</h2><p>The GWC page code does not include advertising pixels, visitor analytics, cross-site tracking, or browser storage for marketing. It does not change its behavior in response to Do Not Track or Global Privacy Control signals because it does not implement those tracking activities. Hosting and sign-in services operate separately.</p><h2>Questions, corrections, and changes</h2><p>To ask about, review, or request a correction to information you have sent GWC, contact Lew at <a href="mailto:lweiner@gwcis.com">lweiner@gwcis.com</a> or <a href="tel:+13109203603">(310) 920-3603</a>, or write to GWC Information Systems, LLC, 18375 Ventura Blvd., #801, Tarzana, CA 91356-4218. Changes to this website notice will appear on this page with an updated effective date.</p></main>;
}


export const dynamic = 'force-static';
